version: '3.4'
services:
  php:
    build:
      context: php
    restart: unless-stopped
    ports:
      - "8080:80"
    links:
      - mysql
  mysql:
    image: mysql:8.0.22
    command:
      --default-authentication-plugin=mysql_native_password --sql-mode=NO_ENGINE_SUBSTITUTION
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    tmpfs: /var/lib/mysql
